### ISSUE TITLE
HTTPS redirect

### ISSUE THREAD

**Issue by rugk** [imazen/imageflow-web#3]
Without HTTPS I cannot believe you "put security first" as stated on the site. I mean the information that you claim to do so, could be modified… 😉 

https://doesmysiteneedhttps.com/

**Comment by rugk** [comment]
Ah, just noticed you already offer HTTPS. So please make it default. And if you already use Cloudflare make sure it is set to "Full SSL (Strict)" so that it verifies the connection to the upstream server.

**Comment by lilith** [comment]
HTTPS was set to default early this year (I do periodic audits), but regressed sometime later. I just had a strange experience where the "Always use HTTPS" setting reverted when I refreshed the page. I'm going to investigate this further.  Full SSL is used, but (Strict) is not compatible with github pages - the common names do not match.
